export const de = {
    title: 'Entscheidungsbäume',
    subtitle: 'Ein Lerntool zum verstehen von Entcheidungsbäumen',
    trees: 'Binärbäume',
    root: 'Stamm',
    node: 'Knoten',
    lorem: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer',
    footer: 'Designed und entwickelt von André Peters',
    game: 'Spiel',
    generator: 'Generator',
    result: 'Ergebnis',
    lv2Decision: 'Wie ist das Wetter',
    hot: 'Warm',
    windy: 'Windig',
    rainy: 'Regnerisch',
    lv3Decision: 'Tennis spielen',
    outlook: 'Ausblick',
    temperature: 'Temperatur',
    humidity: 'Feuchtigkeit',
    no: 'Nein',
    yes: 'Ja',
    sunny: 'Sonnig',
    overcast: 'Wolkig',
    cool: 'Kühl',
    mild: 'Mild',
    high: 'Hoch',
    normal: 'Normal',
    bad_weather: 'Schlechtes Wetter',
    good_weather: 'Gutes Wetter',
    check_code: 'Prüfe Baum',
    clear_workspace: 'Arbeitsbereich löschen',
    show_tree: 'Baumdiagramm anzeigen',
    reset: 'Zurücksetzen',
    back: 'Zurück',
    next: 'Weiter',
    show_result: 'Ergebnis anzeigen',
    lv1Decision: 'Welches Tier?',
    feathers: 'Hat es Federn?',
    fly: 'Kann es Fliegen?',
    ground: 'Lebt es unter der Erde?',
    mole: 'Maulwurf',
    dog: 'Hund',
    penguin: 'Pinguin',
    crow: 'Rabe',
    leaf_tooltip: 'Das ist ein Blatt, es repräsentiert deine Entscheidung',
    node_tooltip: 'Das ist ein Knoten, er verbindet sich mit anderen Knoten oder mit einem Blatt',
    level1_description: 'In einem Forschungslabor werden vier Tiere untersucht: ein Rabe, ein Pinguin, ein Maulwurf und ein Hund. Jedes dieser Tiere hat unterschiedliche Merkmale und Fähigkeiten, die es von den anderen Tieren unterscheidet. Die Forscher wollen mithilfe eines Entscheidungsbaums herausfinden, welches Tier fliegen kann, welches unter der Erde lebt und welches Federn hat.',
    level1_task: 'Die Aufgabe lautet wie folgt: Bestimme anhand der Merkmale "Federn", "Fliegen" und "Leben unter der Erde", welches Tier zu welchen Eigenschaften gehört. Reicht der gegebene Entscheidungsbaum aus um die Tiere eindeutig zu unterscheiden? Füge gegebenfalls noch weitere Entscheidungen ein. Prüfe deinen Baum wenn du dir sicher bist!', 
    leaf_missing: 'Blatt fehlt!',
    node_missing: 'Entscheidung fehlt!',
    block_intro_1: 'Dürfen wir vorstellen: Dein Werkzeug für die kommenden Level. Dies ist der reguläre Block um einen Entscheidungsbaum zu erstellen. Du wirst ihn für alle Level nutzen müssen.',
    not_again: 'Nicht nochmal zeigen',
    block_intro_title: 'Einleitung: Block',
    block_intro_2: 'Standardmäßig hat der Block "nur" zwei Wahl Möglichkeiten, du wirst jedoch bemerken, dass du teilweise mehr als nur eine Wahl benötigst. Um den Block dafür zu erweitern gibt es das Plus Symbol an der oberen Linken Ecke des Blocks. Wenn du auf dieses drückst kannst du den Knoten um eine Wahl erweitern. Danach erscheint auch ein Minus Symbol zum entfernen der zuletzt hinzugefügten Wahl.',
    block_intro_3: 'Hier kannst du eine der gegebenen Wahl Möglichkeiten auswählen. Es kann unterschiedlich viele Wahlen geben, je nachdem solltest du den Block erweitern um alle Wahlen abzudecken. Falls du eine Wahl doppelt belegst wird nur die unterste Wahl innerhalb des Blocks ausgewertet. Belege aus diesem Grund nur jede Wahl einmal.',
    done: 'fertig',
    show_json: 'JSON Anzeigen',
    analyse_title: 'Analyse: Block',
    advice: 'Tipp',
    json_error: 'Kein zusammenhängender Baum',
    

}