/**
 *  German translations
 */
export const de = {
    title: 'Entscheidungsbäume',
    subtitle: 'Ein Lerntool zum verstehen von Entcheidungsbäumen',
    trees: 'Binärbäume',
    root: 'Stamm',
    node: 'Knoten',
    lorem: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer',
    footer: 'Designed und entwickelt von André Peters',
    game: 'Spiel',
    generator: 'Generator',
    result: 'Ergebnis',
    hot: 'Warm',
    windy: 'Windig',
    rainy: 'Regnerisch',
    outlook: 'Ausblick',
    temperature: 'Temperatur',
    humidity: 'Feuchtigkeit',
    no: 'Nein',
    yes: 'Ja',
    sunny: 'Sonnig',
    overcast: 'Wolkig',
    cool: 'Kühl',
    mild: 'Mild',
    high: 'Hoch',
    normal: 'Normal',
    bad_weather: 'Schlechtes Wetter',
    good_weather: 'Gutes Wetter',
    check_code: 'Prüfe Baum',
    clear_workspace: 'Arbeitsbereich löschen',
    show_tree: 'Baumdiagramm anzeigen',
    reset: 'Zurücksetzen',
    back: 'Zurück',
    next: 'Weiter',
    show_result: 'Ergebnis anzeigen',
    level3_decision: 'Welches Tier?',
    feathers: 'Hat es Federn?',
    fly: 'Kann es Fliegen?',
    ground: 'Lebt es unter der Erde?',
    mole: 'Maulwurf',
    dog: 'Hund',
    penguin: 'Pinguin',
    crow: 'Rabe',
    leaf_tooltip: 'Das ist ein Blatt, es repräsentiert deine Entscheidung',
    node_tooltip: 'Das ist ein Knoten, er verbindet sich mit anderen Knoten oder mit einem Blatt',
    level1_description: 'In einem Forschungslabor werden vier Tiere untersucht: ein Rabe, ein Pinguin, ein Maulwurf und ein Hund. Jedes dieser Tiere hat unterschiedliche Merkmale und Fähigkeiten, die es von den anderen Tieren unterscheidet. Die Forscher wollen mithilfe eines Entscheidungsbaums herausfinden, welches Tier fliegen kann, welches unter der Erde lebt und welches Federn hat.',
    level1_task: 'Die Aufgabe lautet wie folgt: Bestimme anhand der Merkmale "Federn", "Fliegen" und "Leben unter der Erde", welches Tier zu welchen Eigenschaften gehört. Reicht der gegebene Entscheidungsbaum aus um die Tiere eindeutig zu unterscheiden? Füge gegebenfalls noch weitere Entscheidungen ein. Prüfe deinen Baum wenn du dir sicher bist!', 
    leaf_missing: 'Blatt fehlt!',
    node_missing: 'Entscheidung fehlt!',
    block_intro_1: 'Dürfen wir vorstellen: Dein Werkzeug für die kommenden Level. Dies ist der reguläre Block um einen Entscheidungsbaum zu erstellen. Du wirst ihn für alle Level nutzen müssen.',
    not_again: 'Nicht nochmal zeigen',
    block_intro_title: 'Einleitung: Block',
    block_intro_2: 'Standardmäßig hat der Block "nur" zwei Wahl Möglichkeiten, du wirst jedoch bemerken, dass du teilweise mehr als nur eine Wahl benötigst. Um den Block dafür zu erweitern gibt es das Plus Symbol an der oberen Linken Ecke des Blocks. Wenn du auf dieses drückst kannst du den Knoten um eine Wahl erweitern. Danach erscheint auch ein Minus Symbol zum entfernen der zuletzt hinzugefügten Wahl.',
    block_intro_3: 'Hier kannst du eine der gegebenen Wahl Möglichkeiten auswählen. Es kann unterschiedlich viele Wahlen geben, je nachdem solltest du den Block erweitern um alle Wahlen abzudecken. Falls du eine Wahl doppelt belegst wird nur die unterste Wahl innerhalb des Blocks ausgewertet. Belege aus diesem Grund nur jede Wahl einmal.',
    done: 'fertig',
    show_json: 'JSON Anzeigen',
    analyse_title: 'Analyse: Block',
    advice: 'Tipp',
    json_error: 'Kein zusammenhängender Baum',
    target: 'Entscheidung',
    tires: 'Reifen',
    car: 'Auto',
    motorcycle: 'Motorrad',
    level1_decision: 'Welches Fahrzeug?',
    level5_description: 'Es war einmal eine leidenschaftliche Tennisspielerin namens Sarah. Sie liebte nichts mehr, als auf den Platz zu gehen und ein paar Sets mit ihren Freunden zu spielen. Sarah wusste jedoch, dass bestimmte Wetterbedingungen ihr Spiel beeinträchtigen könnten. An einem sonnigen Morgen wachte Sarah auf und überprüfte die Wetter-App auf ihrem Telefon. Sie sah, dass die Temperatur 85 Grad Fahrenheit betrug, die Luftfeuchtigkeit 70 % betrug, der Wind 8 Meilen pro Stunde wehte und die Aussicht teilweise bewölkt war. Sarah wusste, dass diese Faktoren über Erfolg oder Misserfolg ihres Tennisspiels entscheiden konnten. Sie begann über ihre Vorlieben für jeden dieser Faktoren nachzudenken. Es machte ihr nichts aus, bei warmem Wetter zu spielen, aber 85 Grad könnten ihr zu schaffen machen. Sie bevorzugte eine Luftfeuchtigkeit unter 60 % und eine Windgeschwindigkeit von nicht mehr als 5 Meilen pro Stunde. Was die Aussichten angeht, machte es ihr nichts aus, bei teilweise bewölkten Bedingungen zu spielen, aber sie bevorzugte einen sonnigen Tag. Also beschloss Sarah, eine Entscheidung basierend auf ihren Vorlieben zu treffen. Sie überprüfte die Temperatur und stellte fest, dass es für ihren Geschmack etwas zu heiß war. Auch die Luftfeuchtigkeit war etwas hoch und der Wind war stärker als ihr lieb war. Sie schaute auf die Aussicht und sah, dass es teilweise bewölkt war. Nachdem sie all diese Faktoren berücksichtigt hatte, beschloss Sarah, für diesen Tag auf Tennis zu verzichten. Sie wusste, dass die Wetterbedingungen es schwierig machen könnten, ihr bestes Spiel zu spielen, und sie wollte keine Verletzungen oder Frustrationen riskieren. Stattdessen entschied sie sich, zu Hause zu bleiben, sich zu entspannen und an einem anderen Tag Tennis zu spielen, wenn das Wetter ihr besser gefiel.',
    level5_task: 'Versuchen Sie, Sarah zu helfen und erstellen Sie einen Entscheidungsbaum, der ihre Entscheidung vorhersagt!',
    level2_description: 'Keine daten',
    level2_task: 'keine Daten',
    level3_description: 'Keine daten',
    level3_task: 'keine Daten',
    level4_description: 'Keine daten',
    level4_task: 'keine Daten',
    level4_decision: 'Wie ist das Wetter',
    level5_decision: 'Tennis spielen',
    generator_description: 'Dies ist der Generator. Hier können Sie Ihre Fähigkeiten anhand des ID3-Algorithmus für maschinelles Lernen testen. Erstellen Sie einen Datensatz und versuchen Sie, ihn durch die Erstellung eines Entscheidungsbaums zu lösen.',
    level2_decision: 'Obst oder Gemüse?',
    sweet: 'süß',
    salty: 'salzig',
    bitter: 'bitter',
    sour: 'sauer',
    fruit: 'Obst',
    vegetables: 'Gemüse',
    taste: 'Geschmack',
    random_test: 'Zufälligen Test hinzufügen',
    generator_step1: 'Bitte trage hier ein welche Entscheidung du mithilfe des Baums treffen möchtest. Es kann sich um alles deiner Wahl handeln, jedoch kannst du deine Wahl nicht mehr ändern.',
    generator_step2: 'Hier kannst du nun deine Features einfügen, die bestimmen für welche Entscheidung wir uns entscheiden bzw. woran man deine Entscheidung messen kann. Ein Beispiel wäre, dass du anhand von Fell einen Hund von einem Menschen unterscheiden kannst.',
    generator_step3: 'Fülle hier deine Tabelle mit Leben! Du solltest für jede Entscheidung alle Parameter ausfüllen.',
    decision: 'Entscheidung',
    features: 'Features',
    data: 'Daten',
    generator_title: 'Erstelle dir dein Eigenes Level!',
    valid_features: 'Es gibt noch unbelegte Features!',
    enough_features: 'Es sind noch nicht genügend Features definiert worden!',
    missing_data: 'Es fehlen noch daten in der Tabelle!',
    correct: 'Richtig',
    incorrect: 'Falsch',
    guessed: 'Vorhersage',

}