/**
 *  English Translations
 */
export const en = {
    title: 'Decision Trees',
    subtitle: 'A Learntool to understand Machine Learning Techniques',
    trees: 'Binary Trees',
    root: 'Root',
    node: 'Node',
    lorem: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer',
    footer: 'Designed and developed by André Peters',
    game: 'Game',
    generator: 'Generator',
    result: 'Result',
    lv2Decision: 'How is the Weather',
    hot: 'Hot',
    windy: 'Windy',
    rainy: 'Rainy',
    lv3Decision: 'Play Tennis',
    outlook: 'Outlook',
    temperature: 'Temperature',
    humidity: 'Humidity',
    no: 'No',
    yes: 'Yes',
    sunny: 'Sunny',
    overcast: 'Overcast',
    cool: 'Cool',
    mild: 'Mild',
    high: 'High',
    normal: 'Normal',
    bad_weather: 'Bad weather',
    good_weather: 'Good weather',
    check_code: 'Check code',
    clear_workspace: 'Clear workspace',
    show_tree: 'Show tree graph',
    reset: 'Reset',
    back: 'Back',
    next: 'Next',
    show_result: 'Show result',
    level3_decision: 'Which animal?',
    feathers: 'Has feathers?',
    fly: 'Can fly?',
    ground: 'Lives underground?',
    mole: 'Mole',
    dog: 'Dog',
    penguin: 'Penguin',
    crow: 'Crow',
    leaf_tooltip: 'This is a leaf, it represents your Decision',
    node_tooltip: 'This is a Node it connects with other Nodes or Leafs',
    level1_description: 'Four animals are being studied in a research laboratory: a raven, a penguin, a mole and a dog. Each of these animals has different characteristics and abilities that set them apart from the other animals. The researchers want to use a decision tree to find out which animal can fly, which lives underground and which has feathers.',
    level1_task: 'The task is as follows: using the characteristics "feathers", "flies" and "life under the earth", determine which animal belongs to which properties. Is the given decision tree sufficient to clearly distinguish between the animals? If necessary, add further decisions. Check your tree if you are sure!',
    leaf_missing: 'Leaf is missing!',
    node_missing: 'Decision is missing!',
    block_intro_1: 'May we introduce: Your tool for the coming levels. This is the regular block to build a decision tree. You will have to use it for all levels.',
    not_again: 'Do not show again',
    block_intro_title: 'Introduction: Block',
    block_intro_2: 'By default, the block "only" has two choices, but you\'ll notice that you sometimes need more than one choice. To expand the block for this there is the plus icon at the top left corner of the block. If you press on this you can expand the node by one choice. After that, a minus symbol will also appear to remove the last choice added.',
    block_intro_3: 'Here you can select one of the given options. There can be different number of choices, so you should expand the block to cover all choices. If you use a choice twice, only the bottom choice within the block will be evaluated. For this reason, only record each election once.',
    done: 'done',
    show_json: 'Show JSON',
    analyse_title: 'Analyse: Block',
    advice: 'Advice',
    json_error: 'No contiguous tree',
    target: 'Decision',
    tires: 'Tires',
    car: 'Car',
    motorcycle: 'Motorcycle',
    level1_decision: 'Which Vehicle?',
    level5_description: 'Once upon a time, there was a passionate tennis player named Sarah. She loved nothing more than hitting the court and playing a few sets with her friends. However, Sarah knew that certain weather conditions could impact her game. One sunny morning, Sarah woke up and checked the weather app on her phone. She saw that the temperature was 85 degrees Fahrenheit, the humidity was 70%, the wind was 8 miles per hour, and the outlook was partly cloudy. Sarah knew that these factors could either make or break her tennis game. She started to think about her preferences for each of these factors. She didn\'t mind playing in warm weather, but 85 degrees might be pushing it. She preferred the humidity to be lower than 60%, and the wind to be no more than 5 miles per hour. As for the outlook, she didn\'t mind playing in partly cloudy conditions, but she preferred a sunny day. So Sarah decided to make a decision based on her preferences. She checked the temperature and saw that it was a bit too hot for her liking. The humidity was also a bit high, and the wind was stronger than she preferred. She looked at the outlook and saw that it was partly cloudy. After considering all of these factors, Sarah decided to skip tennis for the day. She knew that the weather conditions could make it difficult to play her best game, and she didn\'t want to risk injury or frustration. Instead, she opted to stay home, relax, and plan to play tennis another day when the weather was more to her liking.',
    level5_task: 'Try to help Sarah and create a Decision Tree that predicts her Decision!',
    level2_description: 'Keine daten',
    level2_task: 'keine Daten',
    level3_description: 'Keine daten',
    level3_task: 'keine Daten',
    level4_description: 'Keine daten',
    level4_task: 'keine Daten',
    level4_decision: 'What\'s the weather',
    level5_decision: 'Play Tennis',
    generator_description: 'This is the Generator, here you can test your skills against the ID3 Machine Learning Algorithm. Create a Data Set and try to solve it by creating a Decision Tree.',
    level2_decision: 'Fruits or vegetables?',
    sweet: 'sweet',
    salty: 'salty',
    bitter: 'bitter',
    sour: 'sour',
    fruit: 'Fruit',
    vegetables: 'Vegetables',
    taste: 'Taste',
    random_test: 'Add random test',
    generator_step1: 'Please enter here which decision you would like to make with the help of the tree. It can be anything of your choice, but you cannot change your choice.',
    generator_step2: 'Here you can now add your features that determine which decision we decide on or how you can measure your decision. An example would be that you can tell a dog from a human based on fur.',
    generator_step3: 'Fill your table with life here! You should fill in all the parameters for each decision.',
    decision: 'Decision',
    features: 'Features',
    data: 'Data',
    generator_title: 'Create your own level!',
    valid_features: 'There are still unused features!',
    enough_features: 'Not enough features have been defined yet!',
    missing_data: 'Data is still missing in the table!',
    correct: 'Correct',
    incorrect: 'Wrong',
    guessed: 'Forecast',
}