/**
 *  English Translations
 */
export const en = {
    title: 'Decision Trees',
    subtitle: 'A Learntool to understand Machine Learning Techniques',
    footer: 'Designed and developed by André Peters',
    game: 'Game',
    generator: 'Generator',
    result: 'Result',
    lv2Decision: 'How is the Weather',
    hot: 'Hot',
    windy: 'Windy',
    rainy: 'Rainy',
    lv3Decision: 'Play Tennis',
    outlook: 'Outlook',
    temperature: 'Temperature',
    humidity: 'Humidity',
    no: 'No',
    yes: 'Yes',
    sunny: 'Sunny',
    overcast: 'Overcast',
    cool: 'Cool',
    mild: 'Mild',
    high: 'High',
    normal: 'Normal',
    bad_weather: 'Bad weather',
    good_weather: 'Good weather',
    check_code: 'Check code',
    clear_workspace: 'Clear workspace',
    show_tree: 'Show tree graph',
    reset: 'Reset',
    back: 'Back',
    next: 'Next',
    show_result: 'Show result',
    level3_decision: 'Which animal?',
    feathers: 'Has feathers?',
    fly: 'Can fly?',
    ground: 'Lives underground?',
    mole: 'Mole',
    dog: 'Dog',
    penguin: 'Penguin',
    crow: 'Crow',
    leaf_tooltip: 'This is a leaf, it represents your Decision',
    node_tooltip: 'This is a Node it connects with other Nodes or Leafs',
    level1_description: 'Four animals are being studied in a research laboratory: a raven, a penguin, a mole and a dog. Each of these animals has different characteristics and abilities that set them apart from the other animals. The researchers want to use a decision tree to find out which animal can fly, which lives underground and which has feathers.',
    level1_task: 'The task is as follows: using the characteristics "feathers", "flies" and "life under the earth", determine which animal belongs to which properties. Is the given decision tree sufficient to clearly distinguish between the animals? If necessary, add further decisions. Check your tree if you are sure!',
    leaf_missing: 'Leaf is missing!',
    node_missing: 'Decision is missing!',
    block_intro_1: 'May we introduce: Your tool for the coming levels. This is the regular block to build a decision tree. You will have to use it for all levels.',
    not_again: 'Do not show again',
    block_intro_2: 'At this point in the block, you can choose what the block should represent. In this case, the block represents the "Hot" decision. Using the drop-down menu that appears when you press the arrow, you can choose one of the given decisions for the block to represent. Each block can represent a maximum of one decision.',
    block_intro_title: 'Introduction: Block',
    block_intro_4: 'By default, the block "only" has two choices, but you\'ll notice that you sometimes need more than one choice. To expand the block for this there is the plus icon at the top left corner of the block. If you press on this you can expand the node by one choice. After that, a minus symbol will also appear to remove the last choice added.',
    block_intro_3: 'Here you can select one of the given options. There can be different number of choices, so you should expand the block to cover all choices. If you use a choice twice, only the bottom choice within the block will be evaluated. For this reason, only record each election once.',
    block_intro_5: 'The block is structured like a puzzle piece, you can add a so-called parent block to this block in the upper left corner. The parent block\'s decision is relevant to the child block, since the data has already been split by it. You can add this block to the parent block by simply dragging it to the choice you want to connect it to and dropping it once they have connected.',
    block_intro_6: 'These are the bindings of your block. At this point, you can assign your choices to a following block, which further divides the data or includes a decision. To do this, simply drag the block to the point with the connecting piece from the upper left corner of the block to be connected.',
    block_intro_7: 'With the help of this block you can represent a leaf of the tree, i.e. a decision. Only the decision blocks that represent a decision from the task are made available to you. You can connect this to the decide block using the connector on the left.',
    block_intro_8: 'This is what a tree could look like when you represent it using the blocks. At the moment this block represents the decision about "Hot". If it is Hot, i.e. "Choice 1" is "true", then the decision "Good weather" has been made. Likewise with "Choice 2" and "false" the decision "Bad weather" was made. Have fun creating your first decision trees!',
    done: 'done',
    show_json: 'Show JSON',
    analyse_title: 'Analyse: Block',
    advice: 'Advice',
    json_error: 'No contiguous tree',
    target: 'Decision',
    tires: 'Tires',
    car: 'Car',
    motorcycle: 'Motorcycle',
    level1_decision: 'Which Vehicle?',
    level5_description: 'Once upon a time, there was a passionate tennis player named Sarah. She loved nothing more than hitting the court and playing a few sets with her friends. However, Sarah knew that certain weather conditions could impact her game. One sunny morning, Sarah woke up and checked the weather app on her phone. She saw that the temperature was 85 degrees Fahrenheit, the humidity was 70%, the wind was 8 miles per hour, and the outlook was partly cloudy. Sarah knew that these factors could either make or break her tennis game. She started to think about her preferences for each of these factors. She didn\'t mind playing in warm weather, but 85 degrees might be pushing it. She preferred the humidity to be lower than 60%, and the wind to be no more than 5 miles per hour. As for the outlook, she didn\'t mind playing in partly cloudy conditions, but she preferred a sunny day. So Sarah decided to make a decision based on her preferences. She checked the temperature and saw that it was a bit too hot for her liking. The humidity was also a bit high, and the wind was stronger than she preferred. She looked at the outlook and saw that it was partly cloudy. After considering all of these factors, Sarah decided to skip tennis for the day. She knew that the weather conditions could make it difficult to play her best game, and she didn\'t want to risk injury or frustration. Instead, she opted to stay home, relax, and plan to play tennis another day when the weather was more to her liking.',
    level5_task: 'Try to help Sarah and create a Decision Tree that predicts her Decision!',
    level2_description: 'Keine daten',
    level2_task: 'keine Daten',
    level3_description: 'Keine daten',
    level3_task: 'keine Daten',
    level4_description: 'Keine daten',
    level4_task: 'keine Daten',
    level4_decision: 'What\'s the weather',
    level5_decision: 'Play Tennis',
    generator_description: 'This is the generator. He created your level based on the data you provided. This level has the same functionalities as the levels that have already been created. Using the ID3 machine learning algorithm, the generator can also provide you with a solution if you cannot solve your own level. Have fun solving your level!',
    level2_decision: 'Fruits or vegetables?',
    sweet: 'sweet',
    salty: 'salty',
    bitter: 'bitter',
    sour: 'sour',
    fruit: 'Fruit',
    vegetables: 'Vegetables',
    taste: 'Taste',
    random_test: 'Add random test',
    generator_step1: 'Please enter here which decision you would like to make with the help of the tree. It can be anything of your choice, but you cannot change your choice.',
    generator_step2: 'Here you can now add your features that determine which decision we decide on or how you can measure your decision. An example would be that you can tell a dog from a human based on fur.',
    generator_step3: 'Fill your table with life here! You should fill in all the parameters for each decision.',
    decision: 'Decision',
    features: 'Features',
    data: 'Data',
    generator_title: 'Create your own level!',
    valid_features: 'There are still unused features!',
    enough_features: 'Not enough features have been defined yet!',
    missing_data: 'Data is still missing in the table!',
    correct: 'Correct',
    incorrect: 'Wrong',
    guessed: 'Forecast',
    table: 'Table',
    darkmode: 'Lightning Mode',
    language: 'Language',
    level1_intro: 'This is the 1st level, it serves as a starting point to familiarize yourself with the block.',
    level2_intro: '',
    level3_intro: '',
    level4_intro: '',
    level5_intro: '',
    start_game: '',
    start_generator: '',
    start_start: '',
    info: 'Information',
    start: '',
    decide: '',
    decision_tree: 'Entscheidungsbaum',
    information_gain: 'Informationszuwachs',
    splits: 'Teilungen',
    machine_learning: 'Maschinelles Lernen',
    table_content: 'Table of contents',
    start_machine_learning: '',
    start_decision_trees: '',
    start_splits: '',
    start_information_gain: '',
    analyse: 'Great that you made this level! Below you can see statistics about your created decision tree. If you are not interested in the data or you want to continue, press the "X" in the upper right corner.',
}