/**
 *  Barrel File for lazy imports.
 */
export { lv1_data } from './data/tables'
export { lv2_data } from './data/tables'
export { lv3_data } from './data/tables'
export { lv4_data } from './data/tables'
export { lv5_data } from './data/tables'
export { localizedStrings } from './strings/localization'
export { default as success } from './Assets/lottie_success.json'
export { default as blockClean } from './Assets/block_clean.png'
export { default as blockConnected } from './Assets/block_connected.png'
export { default as blockDecision } from './Assets/block_decision.png'
export { default as blockHighlightedChoices } from './Assets/block_highlighted_choices.png'
export { default as blockHighlightedDecision } from './Assets/block_highlighted_decision.png'
export { default as blockHighlightedLeftConnector } from './Assets/block_highlighted_left_connector.png'
export { default as blockHighlightedPlus } from './Assets/block_highlighted_plus.png'
export { default as blockHighlightedRightConnector } from './Assets/block_highlighted_right_connectors.png'
export { default as block3 } from './Assets/block3.png'
export { default as block4 } from './Assets/block4.png'
export { default as block5 } from './Assets/block5.png'
export { default as blockly1 } from './Assets/blockly1.png'
export { default as SvgComponent } from './Assets/logo_built_with'
export { default as Logo } from './Assets/logo.png'
export { default as UndrawArrow } from './Assets/undraw_arrow.svg'
export { default as UndrawBuildingBlocks } from './Assets/undraw_building_blocks.svg'
export { default as UndrawGaming } from './Assets/undraw_gaming.svg'
export { default as UndrawPageNotFound } from './Assets/undraw_page_not_found.svg'