/**
 *  German translations
 */
export const de = {
    title: 'Entscheidungsbäume',
    subtitle: 'Ein Lerntool zum verstehen von Entcheidungsbäumen',
    footer: 'Designed und entwickelt von André Peters',
    game: 'Spiel',
    generator: 'Generator',
    result: 'Ergebnis',
    hot: 'Warm',
    windy: 'Windig',
    rainy: 'Regnerisch',
    outlook: 'Ausblick',
    temperature: 'Temperatur',
    humidity: 'Feuchtigkeit',
    no: 'Nein',
    yes: 'Ja',
    sunny: 'Sonnig',
    overcast: 'Wolkig',
    cool: 'Kühl',
    mild: 'Mild',
    high: 'Hoch',
    normal: 'Normal',
    bad_weather: 'Schlechtes Wetter',
    good_weather: 'Gutes Wetter',
    check_code: 'Prüfe Baum',
    clear_workspace: 'Arbeitsbereich löschen',
    show_tree: 'Baumdiagramm anzeigen',
    reset: 'Zurücksetzen',
    back: 'Zurück',
    next: 'Weiter',
    show_result: 'Ergebnis anzeigen',
    level3_decision: 'Welches Tier?',
    feathers: 'Hat es Federn?',
    fly: 'Kann es Fliegen?',
    ground: 'Lebt es unter der Erde?',
    mole: 'Maulwurf',
    dog: 'Hund',
    penguin: 'Pinguin',
    crow: 'Rabe',
    leaf_tooltip: 'Das ist ein Blatt, es repräsentiert deine Entscheidung',
    node_tooltip: 'Das ist ein Knoten, er verbindet sich mit anderen Knoten oder mit einem Blatt',
    level1_description: 'Tobi ist drei Jahre alt und lernt gerade zu rechnen. Ihm fällt es allerdings schwer zu zählen, dementsprechend kann er auch nicht gut Motorräder von Autos unterscheiden. Ihm würde ein Entscheidungsbaum bei der Zuordnung sicherlich helfen, hilf ihm und erstelle diesen Entscheidungsbaum!. ',
    level1_task: 'Die Aufgabe lautet wie folgt: Bestimme anhand des Merkmals "Reifen", welches Fahrzeug zu welchen Eigenschaften passt. Prüfe deinen Baum wenn du dir sicher bist!', 
    leaf_missing: 'Blatt fehlt!',
    node_missing: 'Entscheidung fehlt!',
    block_intro_1: 'Dürfen wir vorstellen: Dein Werkzeug für die kommenden Level. Dies ist der reguläre Block um einen Entscheidungsbaum zu erstellen. Du wirst ihn für alle Level nutzen müssen.',
    not_again: 'Nicht nochmal zeigen',
    block_intro_title: 'Einleitung: Block',
    block_intro_2: 'An dieser Stelle des Blocks kannst du die Entscheidung wählen, welche der Block abbilden soll. In diesem Fall stellt der Block die Entscheidung "Hot" dar. Über das DropDown Menü, welches erscheint wenn du den Pfeil drückst, kannst du dir eine der gegebenen Entscheidungen aussuchen, die der Block darstellen soll. Jeder Block kann maximal eine Entscheidung darstellen.',
    block_intro_4: 'Standardmäßig hat der Block "nur" zwei Wahl Möglichkeiten, du wirst jedoch bemerken, dass du teilweise mehr als zwei Wahlen benötigst. Um den Block dafür zu erweitern gibt es das Plus Symbol an der oberen Linken Ecke des Blocks. Wenn du auf dieses drückst kannst du den Block um eine Wahl erweitern. Danach erscheint auch ein Minus Symbol zum entfernen der zuletzt hinzugefügten Wahl.',
    block_intro_3: 'Hier kannst du eine der gegebenen Wahl Möglichkeiten auswählen. Es kann unterschiedlich viele Wahlen geben, je nachdem solltest du den Block erweitern um alle Wahlen abzudecken. Falls du eine Wahl doppelt belegst, wird nur die unterste Wahl innerhalb des Blocks ausgewertet. Belege aus diesem Grund nur jede Wahl einmal. Auch hier erscheint ein DropDown Menü, wenn du den Pfeil drückst, um die zu verteilenden Wahlen auswählen zu können.',
    block_intro_5: 'Der Block ist wie ein Puzzlestück aufgebaut, du kannst an der oberen linken Ecke diesem Block einen sogenannten Elternblock hinzufügen. Die Entscheidung des Elternblocks ist relevant für den Kinderblock, da die Daten dann bereits geteilt wurden. Du kannst diesen Block an den Elternblock hinzufügen, indem du ihn einfach zu der Wahlmöglichkeit ziehst mit der du ihn verbinden möchtest und loslässt sobald diese sich verbunden haben.',
    block_intro_6: 'Dies sind die Anbindungen deines Blocks. An dieser Stelle kannst du deinen Wahlen einen Folgeblock zuweisen, welche die Daten noch weiter teilt oder eine Entscheidung beinhaltet. Auch dazu ziehst du den Block einfach an die Stelle mit dem Verbindungsstück aus der oberen linken Ecke des zu verbindenen Blocks.',
    block_intro_7: 'Mithilfe dieses Blocks kannst du ein Blatt des Baums, also eine Entscheidung, darstellen. Es werden dir immer nur die Entscheidungsblöcke zur Verfügung gestellt, welche eine Entscheidung aus der Aufgabe darstellen. Du kannst diesen mithilfe des Konnektors auf der linken Seite mit dem Block zum Entscheiden verbinden.',
    block_intro_8: 'So könnte ein Baum dann am Ende aussehen, wenn du diesen mithilfe der Blöcke darstellst. Momentan bildet dieser Block also die Entscheidung über "Hot" dar. Wenn es Hot ist, also "Choice 1" "true" ist, dann ist die Entscheiung "Good weather" gefallen. Genauso bei "Choice 2" und "false" ist die Entscheiundg "Bad weather" gefallen. Dieses Beispiel verwendet Englische Begriffe in den Bildern, die Anwendung wird dir die Blöcke sowie Entscheidungen jedoch auf Deutsch anzeigen. Viel Spaß beim Erstellen deiner ersten Entscheidungsbäume!',
    done: 'fertig',
    show_json: 'JSON Anzeigen',
    analyse_title: 'Analyse: Block',
    advice: 'Tipp',
    json_error: 'Kein zusammenhängender Baum',
    target: 'Entscheidung',
    tires: 'Reifen',
    car: 'Auto',
    motorcycle: 'Motorrad',
    level1_decision: 'Welches Fahrzeug?',
    level5_description: 'Es war einmal eine leidenschaftliche Tennisspielerin namens Sarah. Sie liebte nichts mehr, als auf den Platz zu gehen und ein paar Sets mit ihren Freunden zu spielen. Sarah wusste jedoch, dass bestimmte Wetterbedingungen ihr Spiel beeinträchtigen könnten. An einem sonnigen Morgen wachte Sarah auf und überprüfte die Wetter-App auf ihrem Telefon. Sie sah, dass die Temperatur Warm war, die Feuchtigkeit Hoch war, es Windig war und die Aussicht bewölkt war. Sarah wusste, dass diese Faktoren über Erfolg oder Misserfolg ihres Tennisspiels entscheiden konnten. Sie begann über ihre Vorlieben für jeden dieser Faktoren nachzudenken. Es machte ihr nichts aus, bei warmem Wetter zu spielen. Sie bevorzugte eine normale Feuchtigkeit und keinen Wind. Was die Aussichten angeht, machte es ihr nichts aus, bei bewölkten Bedingungen zu spielen, aber sie bevorzugte einen sonnigen Tag. Also beschloss Sarah, eine Entscheidung basierend auf ihren Vorlieben zu treffen. Sie überprüfte die Temperatur und stellte fest, dass es für ihren Geschmack etwas zu warm war. Auch die Feuchtigkeit war etwas hoch und der Wind war stärker als ihr lieb war. Sie schaute auf die Aussicht und sah, dass es bewölkt war. Nachdem sie all diese Faktoren berücksichtigt hatte, beschloss Sarah, für diesen Tag auf Tennis zu verzichten. Sie wusste, dass die Wetterbedingungen es schwierig machen könnten, ihr bestes Spiel zu spielen, und sie wollte keine Verletzungen oder Frustrationen riskieren. Stattdessen entschied sie sich, zu Hause zu bleiben, sich zu entspannen und an einem anderen Tag Tennis zu spielen, wenn das Wetter ihr besser gefiel.',
    level5_task: 'Die Aufgabe lautet wie folgt: Versuchen Sie, Sarah zu helfen und erstellen Sie einen Entscheidungsbaum, der ihre Entscheidung vorhersagt!',
    level2_description: 'In einem wunderschönen Garten namens "Geschmacksreich" wachsen eine Vielzahl von Obst- und Gemüsesorten. Dieser Garten wird von einem klugen und neugierigen Botaniker namens Max gepflegt. Max möchte den Besuchern des Gartens helfen, Obst und Gemüse anhand ihres Geschmacks zu unterscheiden. Deswegen beschloss Max eines Tages, einen Entscheidungsbaum zu erstellen, um seinen Kunden bei der Auswahl von Obst und Gemüse zu helfen.',
    level2_task: 'Die Aufgabe lautet wie folgt: Max ist nur ein Botaniker und kennt sich nicht so gut mit Entscheidungsbäumen aus. Hilf ihm dabei und erstelle für ihn einen Entscheidungsbaum, der "Obst" von "Gemüse" unterscheidet.',
    level3_description: 'In einem Forschungslabor werden vier Tiere untersucht: ein Rabe, ein Pinguin, ein Maulwurf und ein Hund. Jedes dieser Tiere hat unterschiedliche Merkmale und Fähigkeiten, die es von den anderen Tieren unterscheidet. Die Forscher wollen mithilfe eines Entscheidungsbaums herausfinden, welches Tier fliegen kann, welches unter der Erde lebt und welches Federn hat.',
    level3_task: 'Die Aufgabe lautet wie folgt: Bestimme anhand der Merkmale "Federn", "Fliegen" und "Leben unter der Erde", welches Tier zu welchen Eigenschaften gehört. Reicht der gegebene Entscheidungsbaum aus um die Tiere eindeutig zu unterscheiden? Füge gegebenfalls noch weitere Entscheidungen ein. Prüfe deinen Baum wenn du dir sicher bist!',
    level4_description: 'In einem kleinen Dorf namens Sonnenheim lebt eine Wetterfee namens Luna. Luna hat die besondere Gabe, das Wetter vorhersagen zu können und den Menschen in Sonnenheim zu helfen, ihre Aktivitäten entsprechend zu planen. Eines Morgens wacht Luna auf und sieht aus dem Fenster. Sie bemerkt, dass die Sonne hell am Himmel strahlt und beschließt, den Dorfbewohnern mitzuteilen, ob das Wetter gut oder schlecht sein würde. Um diese Entscheidung zu treffen, möchte sie einen magischen Entscheidungsbaum erstellen. Dieser soll anhand von den Merkmalen "Windig", "Regnerisch" und "Warm" entscheiden wie das Wetter ist, damit Luna auch in Zukunft das Wetter den Dorfbewohnern mitteilen kann!',
    level4_task: 'Die Aufgabe lautet wie folgt: Hilf Luna dabei ihren magischen Entscheidungsbaum fertigzustellen, der das Wetter vorhersagen kann, um den Dorfbewohner zu helfen.',
    level4_decision: 'Wie ist das Wetter',
    level5_decision: 'Tennis spielen',
    generator_description: 'Dies ist der Generator. Dieser hat dein Level anhand der von dir angegeben Daten erstellt. Dieses Level besitzt dieselben Funktionalitäten wie die bereits fertig erstellten Level. Mithilfe des ID3 Maschine Learning Algorithmus kann der Generator dir auch eine Lösung zur verfügung stellen, falls du dein eigenes Level nicht gelöst bekommst. Viel Spaß beim lösen deines Levels!',
    level2_decision: 'Obst oder Gemüse?',
    sweet: 'süß',
    salty: 'salzig',
    bitter: 'bitter',
    sour: 'sauer',
    fruit: 'Obst',
    vegetables: 'Gemüse',
    taste: 'Geschmack',
    random_test: 'Zufälligen Test hinzufügen',
    generator_step1: 'Bitte trage hier ein welche Entscheidung du mithilfe des Baums treffen möchtest. Es kann sich um alles deiner Wahl handeln, jedoch kannst du deine Wahl nicht mehr ändern.',
    generator_step2: 'Hier kannst du nun deine Features einfügen, die bestimmen für welche Entscheidung wir uns entscheiden bzw. woran man deine Entscheidung messen kann. Ein Beispiel wäre, dass du anhand von Fell einen Hund von einem Menschen unterscheiden kannst.',
    generator_step3: 'Fülle hier deine Tabelle mit Leben! Du solltest für jede Entscheidung alle Parameter ausfüllen.',
    decision: 'Entscheidung',
    features: 'Features',
    data: 'Daten',
    generator_title: 'Erstelle dir dein Eigenes Level!',
    valid_features: 'Es gibt noch unbelegte Features!',
    enough_features: 'Es sind noch nicht genügend Features definiert worden!',
    missing_data: 'Es fehlen noch daten in der Tabelle!',
    correct: 'Richtig',
    incorrect: 'Falsch',
    guessed: 'Vorhersage',
    table: 'Tabelle',
    darkmode: 'Helligkeits Modus',
    language: 'Sprache',
    level1_intro: 'Dies ist das 1. Level, es dient als Einstieg, um sich mit dem Block vertraut zu machen.',
    level2_intro: 'In diesem Level soll die Funktionalität des Erweiterns eines Blocks gelernt & angewendet werden.',
    level3_intro: 'Dieses Level behandelt das Teilen des Datensatzes in optimale Teilmengen, um die meisten Informationen zu erhalten.',
    level4_intro: 'In diesem Level ist besondere Vorsicht geboten, da unter Umständen nicht alle Daten Informationen liefern.',
    level5_intro: 'Dies ist das 5. und letzte Level, hier werden deine neu erlenten Fähigkeiten unter die Probe gestellt!',
    start_game: 'Hier kannst du dein Können auf die Probe stellen, es werden dir 5 verschiedene Level geboten, um einen Entscheidungsbaum zu erstellen. Der Baum wird mithilfe von Blöcken erstellt, dies wird dir dort auch erklärt. Schau doch mal rein!',
    start_generator: 'Hier kannst du dir dein eigenes Level erstellen! Gib zuerst beliebige Daten ein, der Generator erstellt dir dein Level und im Anschluss kannst du für deine eigenen Daten einen Entscheidungsbaum erstellen oder erstellen lassen!',
    start_start: 'Wenn du auf dieser Seite bleibst werden dir die Grundlagen von den Entscheidungsbäumen erläutert, welche dir dann für das Spiel helfen werden um einen Entscheidungsbaum erstellen zu können. Genau die richtige Wahl für Einsteiger!',
    info: 'Informationen',
    start: 'Dies ist ein Prototyp eines Lernwerkzeuges zum Lernen von Entscheidungsbäumen. Es kann dir dabei helfen die Grundlagen zu verstehen und diese anzuwenden. Dazu bietet dir die Anwendung drei Möglichkeiten zum auswählen. Wenn du bereits weißt was Entscheidungsbäume sind und wie man diese erstellt, dann kannst du diese Einführung überspringen und direkt mit einen der zwei weiteren Möglichkeiten weiter machen und die Theorie in der Praxis anwenden! Falls du dich jedoch nicht mit dem Thema auskennst oder dein Wissen wieder etwas auffrischen möchtest, dann solltest du dich entscheiden hier zu bleiben.',
    decide: 'Entscheide dich selber ...',
    decision_tree: 'Entscheidungsbaum',
    information_gain: 'Informationszuwachs',
    splits: 'Teilungen',
    machine_learning: 'Maschinelles Lernen',
    table_content: 'Inhaltsverzeichnis',
    start_machine_learning: 'Maschinelles Lernen stellt ein Teilgebiet der Künstlichen Intelligenz dar, welches nach der Veröffentlichung von ChatGPT jedem ein Begriff sein sollte. Der Begriff Maschinelles Lernen wurde bereits 1959 eingeführt, jedoch fand es keine Nutzung. Erst als in den 1990er Jahren der Spamfilter maschinelles Lernen verwendete wurde das Maschinelle Lernen populär. Heutzutage findet Maschinelles Lernen häufigen Einsatz in der modernen Informatik. Dies auch nicht ohne Grund, es bietet sich in vielerlei Hinsichten an das Maschinelle Lernen zu verwenden. Denn wenn es darum geht etwas zu klassifizieren oder einen Wert zu bestimmen, bietet es sich an einen Maschinell lernenden Algorithmus zu schreiben, der diese Werte klassifiziert oder vorhersagt. Dabei kann das Maschinelle Lernen in drei Arten unterteilt werden, dem überwachten, unüberwachten und bestärkenden Lernen. Bei dem bestärkenden Lernen erhält der Computer Belohnungen oder Bestrafungen, wenn er eine Aufgabe löst oder gelöst hat. Es wird dabei versucht die Lösung zu lernen, welche die größte Belohnung beinhaltet. Beim unüberwachten Lernen erhält der Computer keine Informationen über eine gewünschte Lösung anhand von Belohnungen oder Ähnliches. Der Computer muss anhand von einem Datensatz Muster innerhalb von diesen Daten finden und kann diese daraufhin klassifizieren. Diese Arten sind jedoch nicht interresant für die Entscheidungsbäume, denn diese gehören zu dem überwachten Lernen. Bei dem überwachten Lernen erhält der Computer für jeden Datensatz ein Ergebnis zum Trainieren. Daraufhin werden die Daten in die jeweils möglichen Klassen klassifiziert. Wenn wir zum Beispiel zurück auf das Beispiel mit dem Spamfilter greifen, da könnten zehn verschiedene E-Mails einen Trainingsdatensatz darstellen, wobei jede dieser E-Mails bereits nach Spam oder kein Spam klassifiziert wurde. Dadurch lernt der Computer Merkmale anhand dessen er die E-Mails auch in Zukunft voneinander trennen kann.',
    start_decision_trees: 'Ein Entscheidungsbaum stellt einen mehrstufigen Entscheidungsprozess mit allen Entscheidungsoptionen dar. Da die Entscheidungswege durch einzelne Äste dargestellt werden, spricht man auch von einem Baumdiagramm. Es ist eine Visualisierung und dient als Entscheidungshilfe. Oftmals findet man im Internet Beispiele für Entscheidungsbäume, die zwar alternative Wege in einem Ablauf visualisieren, die aber nicht als Entscheidungshilfe taugen. Der Sinn eines Entscheidungsbaums liegt darin, anhand von verschiedenen, visualisierten Antwortoptionen auf konkrete Fragen zu einer finalen Entscheidung zu gelangen. Auch wenn ein Entscheidungsbaum optisch ansprechend sein kann, ist er durch formale Regeln klar strukturiert. Darin liegt auch der größte Vorteil für Anwender, die diese Regeln leicht über mehrere Ebenen – die Fragen mit Ihren Antwortoptionen – nachvollziehen und so eine Entscheidung treffen können.',
    start_splits: '',
    start_information_gain: '',
    analyse: 'Sehr gut, dass du dieses Level geschafft hast! Im folgenden siehst du Statistiken über deinen erstellten Entscheidungsbaum. Wenn dich die Daten nicht interessieren oder du weiter machen möchtest drücke oben rechts auf das "X".',
}