/**
 *  English Translations
 *  Most of the translations got translated by Google
 *  (Level Descriptions (levelX_description) got AI generated)
 */
export const en = {
    title: 'Decision Trees',
    subtitle: 'A learning tool for understanding decision trees',
    footer: 'Designed and developed by André Peters',
    game: 'Game',
    node: 'Node',
    node_decision: 'Feature: ',
    node_value: 'Value ',
    generator: 'Generator',
    result: 'Result',
    lv2Decision: 'How is the Weather',
    hot: 'Hot',
    windy: 'Windy',
    rainy: 'Rainy',
    lv3Decision: 'Play Tennis',
    outlook: 'Outlook',
    temperature: 'Temperature',
    humidity: 'Humidity',
    no: 'No',
    yes: 'Yes',
    sunny: 'Sunny',
    overcast: 'Overcast',
    cool: 'Cool',
    mild: 'Mild',
    high: 'High',
    normal: 'Normal',
    bad_weather: 'Bad weather',
    good_weather: 'Good weather',
    check_code: 'Check code',
    clear_workspace: 'Clear workspace',
    show_tree: 'Show tree graph',
    reset: 'Reset',
    back: 'Back',
    next: 'Next',
    show_result: 'Show result',
    level3_decision: 'Which animal?',
    feathers: 'Has feathers?',
    fly: 'Can fly?',
    ground: 'Lives underground?',
    mole: 'Mole',
    dog: 'Dog',
    penguin: 'Penguin',
    crow: 'Crow',
    leaf_tooltip: 'This is a leaf, it represents your Decision',
    node_tooltip: 'This is a Node it connects with other Nodes or Leafs',
    level1_description: 'Once upon a time, there was a man named Max who owned a car and a motorcycle. One day, he had an accident and couldn\'t remember which vehicle he was driving. All he could recall was the number of tires. He knew that the vehicle had either four or two tires. Max asked his friend Tom for help. Tom was an expert in decision trees and assisted Max in creating a decision tree to determine which vehicle he was driving. Tom asked Max, "Does the vehicle have four tires?" Max replied, "Yes." Tom said, "Then you are driving the car." However, if Max had answered "No," Tom would have asked him, "Does the vehicle have two tires?" If Max had responded "Yes," Tom would have said, "Then you are riding the motorcycle."',
    level1_task: 'The task is as follows: Use the "tire" feature to determine which vehicle matches which properties. Check your tree if you are sure!',
    leaf_missing: 'Leaf is missing!',
    node_missing: 'Decision is missing!',
    block_intro_1: 'May we introduce: Your tool for the coming levels. This is the regular block to build a decision tree. You will have to use it for all levels.',
    not_again: 'Do not show again',
    block_intro_2: 'At this point in the block, you can choose what the block should represent. In this case, the block represents the "Hot" decision. Using the drop-down menu that appears when you press the arrow, you can choose one of the given decisions for the block to represent. Each block can represent a maximum of one decision.',
    block_intro_title: 'Introduction: Block',
    block_intro_4: 'By default, the block "only" has two choices, but you\'ll notice that you sometimes need more than one choice. To expand the block for this there is the plus icon at the top left corner of the block. If you press on this you can expand the node by one choice. After that, a minus symbol will also appear to remove the last choice added.',
    block_intro_3: 'Here you can select one of the given options. There can be different number of choices, so you should expand the block to cover all choices. If you use a choice twice, only the bottom choice within the block will be evaluated. For this reason, only record each election once.',
    block_intro_5: 'The block is structured like a puzzle piece, you can add a so-called parent block to this block in the upper left corner. The parent block\'s decision is relevant to the child block, since the data has already been split by it. You can add this block to the parent block by simply dragging it to the choice you want to connect it to and dropping it once they have connected.',
    block_intro_6: 'These are the bindings of your block. At this point, you can assign your choices to a following block, which further divides the data or includes a decision. To do this, simply drag the block to the point with the connecting piece from the upper left corner of the block to be connected.',
    block_intro_7: 'With the help of this block you can represent a leaf of the tree, i.e. a decision. Only the decision blocks that represent a decision from the task are made available to you. You can connect this to the decide block using the connector on the left.',
    block_intro_8: 'This is what a tree could look like when you represent it using the blocks. At the moment this block represents the decision about "Hot". If it is Hot, i.e. "Choice 1" is "true", then the decision "Good weather" has been made. Likewise with "Choice 2" and "false" the decision "Bad weather" was made. Have fun creating your first decision trees!',
    done: 'done',
    show_json: 'Show code',
    analyse_title: 'Analyse: Block',
    advice: 'Advice',
    json_error: 'No contiguous tree',
    target: 'Decision',
    tires: 'Tires',
    car: 'Car',
    motorcycle: 'Motorcycle',
    level1_decision: 'Which Vehicle?',
    level5_description: 'Once upon a time, there was a passionate tennis player named Sarah. She loved nothing more than hitting the court and playing a few sets with her friends. However, Sarah knew that certain weather conditions could impact her game. One sunny morning, Sarah woke up and checked the weather app on her phone. She saw that the temperature was 85 degrees Fahrenheit, the humidity was 70%, the wind was 8 miles per hour, and the outlook was partly cloudy. Sarah knew that these factors could either make or break her tennis game. She started to think about her preferences for each of these factors. She didn\'t mind playing in warm weather, but 85 degrees might be pushing it. She preferred the humidity to be lower than 60%, and the wind to be no more than 5 miles per hour. As for the outlook, she didn\'t mind playing in partly cloudy conditions, but she preferred a sunny day. So Sarah decided to make a decision based on her preferences. She checked the temperature and saw that it was a bit too hot for her liking. The humidity was also a bit high, and the wind was stronger than she preferred. She looked at the outlook and saw that it was partly cloudy. After considering all of these factors, Sarah decided to skip tennis for the day. She knew that the weather conditions could make it difficult to play her best game, and she didn\'t want to risk injury or frustration. Instead, she opted to stay home, relax, and plan to play tennis another day when the weather was more to her liking.',
    level5_task: 'Try to help Sarah and create a Decision Tree that predicts her Decision!',
    level2_description: 'A variety of fruits and vegetables grow in a beautiful garden called "Flavourful". This garden is maintained by a clever and curious botanist named Max. Max wants to help visitors to the garden distinguish fruit and vegetables based on their taste. So one day Max decided to create a decision tree to help his customers choose fruit and vegetables.',
    level2_task: 'The task is as follows: Max is just a botanist and doesn\'t know much about decision trees. Help him and create a decision tree for him that distinguishes "fruit" from "vegetables".',
    level3_description: 'Four animals are being studied in a research laboratory: a raven, a penguin, a mole and a dog. Each of these animals has different characteristics and abilities that set them apart from the other animals. The researchers want to use a decision tree to find out which animal can fly, which lives underground and which has feathers.',
    level3_task: 'The task is as follows: using the characteristics "feathers", "flies" and "life under the earth", determine which animal belongs to which properties. Is the given decision tree sufficient to clearly distinguish between the animals? If necessary, add further decisions. Check your tree if you are sure!',
    level4_description: 'In a small village called Sonnenheim lives a weather fairy named Luna. Luna has the special gift of being able to predict the weather and helping the people of Sunhome plan their activities accordingly. One morning Luna wakes up and looks out the window. She notices the sun is shining brightly in the sky and decides to let the villagers know if the weather would be good or bad. To make this decision, she wants to create a magic decision tree. This should decide what the weather is like based on the characteristics "Windy", "Rainy" and "Warm", so that Luna can also inform the villagers about the weather in the future!',
    level4_task: 'The task is as follows: help Luna complete her magic decision tree that can predict the weather to help the villagers.',
    level4_decision: 'What\'s the weather',
    level5_decision: 'Play Tennis',
    generator_description: 'This is the generator. He created your level based on the data you provided. This level has the same functionalities as the levels that have already been created. Using the ID3 machine learning algorithm, the generator can also provide you with a solution if you cannot solve your own level. Have fun solving your level!',
    level2_decision: 'Fruits or vegetables?',
    sweet: 'sweet',
    salty: 'salty',
    bitter: 'bitter',
    sour: 'sour',
    fruit: 'Fruit',
    vegetables: 'Vegetables',
    taste: 'Taste',
    random_test: 'Add random test',
    generator_step1: 'Please enter here which decision you would like to make with the help of the tree. It can be anything of your choice, but you cannot change your choice.',
    generator_step2: 'Here you can now add your features that determine which decision we decide on or how you can measure your decision. An example would be that you can tell a dog from a human based on fur.',
    generator_step3: 'Fill your table with life here! You should fill in all the parameters for each decision.',
    decision: 'Decision',
    features: 'Features',
    data: 'Data',
    generator_title: 'Create your own level!',
    valid_features: 'There are still unused features!',
    enough_features: 'Not enough features have been defined yet!',
    missing_data: 'Data is still missing in the table!',
    correct: 'Correct',
    incorrect: 'Wrong',
    guessed: 'Forecast',
    table: 'Table',
    darkmode: 'Lightning Mode',
    language: 'Language',
    level1_intro: 'This is the 1st level, it serves as a starting point to familiarize yourself with the block.',
    level2_intro: 'In this level the functionality of expanding a block should be learned & applied.',
    level3_intro: 'This level handles dividing the dataset into optimal subsets to get the most information.',
    level4_intro: 'Particular caution is required in this level, since not all data may provide information.',
    level5_intro: 'This is the 5th and final level, this is where your newly learned skills will be put to the test!',
    start_game: 'Here you can put your skills to the test, you are offered 5 different levels to create a decision tree. The tree is created using blocks, this is also explained to you there. Have a look!',
    start_generator: 'Here you can create your own level! First enter any data, the generator will create your level for you and then you can create a decision tree for your own data or have it created!',
    start_start: 'If you stay on this page you will be introduced to the basics of decision trees which will then help you in game to create a decision tree. Exactly the right choice for beginners!',
    info: 'Information',
    start: 'This is a prototype learning tool for learning decision trees. It can help you understand the basics and apply them. The application offers you three options to choose from. If you already know what decision trees are and how to create them, then you can skip this introduction and go straight to one of the two other options and put the theory into practice! However, if you are not familiar with the topic or would like to refresh your knowledge, then you should decide to stay here.',
    decide: 'Decide yourself...',
    decision_tree: 'Decision Tree',
    information_gain: 'Information gain',
    splits: 'Splits',
    machine_learning: 'Machine Learning',
    table_content: 'Table of contents',
    start_machine_learning: 'Machine learning is a sub-area of ​​artificial intelligence, which everyone should be familiar with after the release of ChatGPT. The term machine learning was introduced in 1959, but it was not used. Machine learning only became popular when spam filters used machine learning in the 1990s. Nowadays, machine learning is often used in modern computer science. And not without reason, there are many ways to use machine learning. Because when it comes to classifying something or determining a value, it makes sense to write a machine learning algorithm that classifies or predicts these values. Machine learning can be divided into three types, supervised, unsupervised and reinforcement learning. In reinforcement learning, the computer receives rewards or punishments when it solves or has solved a task. An attempt is made to learn the solution that has the greatest reward. In unsupervised learning, the computer does not receive any information about a desired solution based on rewards or the like. The computer has to use a data set to find patterns within this data and can then classify them. However, these types are not interesting for the decision trees, because these belong to the supervised learning. With supervised learning, the computer receives a result for training for each data set. The data is then classified into the possible classes. For example, if we go back to the spam filter example, ten different emails could constitute a training data set, with each of those emails already classified as spam or not spam. As a result, the computer learns characteristics that it can use to separate the e-mails from one another in the future.',
    start_decision_trees1: 'A decision tree represents a multi-stage decision-making process with all decision-making options. Since the decision-making paths are represented by individual branches, it is also called a tree diagram. It is a visualization and serves as a decision-making aid. You can often find examples of decision trees on the Internet that visualize alternative paths in a process, but are not suitable as a decision-making aid. The purpose of a decision tree is to reach a final decision based on different, visualized answer options to specific questions. Even if a decision tree can be visually appealing, it is clearly structured using formal rules. This is also the greatest advantage for users, who can easily understand these rules over several levels - the questions with their answer options - and thus make a decision.',
    start_decision_trees2: '',
    start_splits: '',
    start_entropy: '',
    start_information_gain: '',
    entropy: 'Entropy',
    feature: 'Feature',
    hint: 'Hint',
    hint_title: 'Do you struggle with a Decision? Tell me where and I will try to help you!',
    hint_leafs: 'You have already made all the questions to find a decision, just choose the right decisions! See the table with the data.',
    hint_description: 'In the following you can see the other decisions and their information gain, this can help you to find the optimal decision!',
    analyse: 'Great that you made this level! Below you can see statistics about your created decision tree. If you are not interested in the data or you want to continue, press the "X" in the upper right corner.',
    leaf: 'Leaf',
    root: 'Root',
    start_tree_decision: 'Was soll ich heute anziehen?',
    start_tree_temperature: 'Wie ist die Temperatur?',
    start_tree_rain: 'Regnet es?',
    start_tree_windy: 'Ist es windig?',
    start_tree_leaf1: 'Regenjacke & lange Hose',
    start_tree_leaf2: 'Pullover & lange Hose',
    start_tree_leaf3: 'Regenjacke & kurze Hose',
    start_tree_leaf4: 'T-Shirt & kurze Hose',
    cold: 'cold',
    warm: 'warm',
}